version: '2'
services:
    reactpoc-app:
        image: reactpoc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reactpoc-mysql:3306/reactpoc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    reactpoc-mysql:
        extends:
            file: mysql.yml
            service: reactpoc-mysql
